### PR TITLE
Chinese Translation of offline voting and readme

### PR DESCRIPTION
**Pull request by anthonyzzy**

### CODE REVIEW

**Comment by abourget** [comment]
whoops, why did you close it ?

**Comment by anthonyzzy** [comment]
@abourget reopened

**Comment by abourget** [comment]
woah.. it's in a weird state right now.. I did resolution through the GitHub UI..

**Comment by anthonyzzy** [comment]
@abourget does that mean we have to wait for a bit longer to have it approved?

**Pull request merged**
